language: php

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
      env: COVERAGE=true
    - php: 7.4
  fast_finish: true

git:
  depth: 1

services:
  - docker

cache:
  directories:
    - $HOME/.composer

before_install:
  - docker-compose -f docker-compose.yaml -f tests/docker-compose.travis.yaml up -d
  - docker ps --all
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi

env:
  global:
    - TOXIPROXY_HOST=localhost TOXIPROXY_AMQP_PORT=5673

before_script:
  - travis_retry composer update --no-interaction --prefer-dist
  - php tests/wait_broker.php

script:
  - vendor/bin/phpunit -d zend.enable_gc=0 --coverage-text --coverage-clover=coverage.clover

after_success: >
  if [[ $COVERAGE = true ]]; then
    wget https://scrutinizer-ci.com/ocular.phar
    php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  fi
