name: Update documentation page

on:
  release:
    types: [published]

jobs:
  run:
    runs-on: ubuntu-latest
    name: Regenerate phpDocumentator docs
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.2
        extensions: ctype, dom, iconv, json, libxml, simplexml, zlib
        coverage: none
    - name: Download phpDocumentator
      run: wget -qN https://github.com/phpDocumentor/phpDocumentor2/releases/download/v2.9.1/phpDocumentor.phar
    - name: Generate docs
      run: php -d error_reporting=1 ./phpDocumentor.phar run --force --template=clean --defaultpackagename=PhpAmqpLib --title='php-amqplib' -d ./PhpAmqpLib -t ./docs
    - name: Commit changes
      run: |
        cd ./docs
        rm -rf ./phpdoc-cache-*
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ./*
        git commit -m "update documentation" || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: ./docs
        branch: gh-pages
        force: true

